{
 "title": "Packets",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "timeseriesdb",
     "rawSql": "SELECT MAX(bytes_transferred) FROM timeseriesdb.packets LIMIT 50 "
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "timeseriesdb",
     "rawSql": "SELECT MIN(bytes_transferred) FROM timeseriesdb.packets LIMIT 50 "
    }
   ]
  },
  {
   "title": "Communication types",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "timeseriesdb",
     "rawSql": "SELECT COUNT(protocol), protocol FROM timeseriesdb.packets GROUP BY protocol LIMIT 50 "
    }
   ]
  },
  {
   "title": "most common ips",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "timeseriesdb",
     "rawSql": "SELECT distinct(src_ip), count(*) FROM timeseriesdb.packets group by src_ip LIMIT 50 "
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "dataset": "timeseriesdb",
     "rawSql": "SELECT timestamp, ttl FROM timeseriesdb.packets LIMIT 50 "
    }
   ]
  },
  {
   "title": "Preview",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 13 },
   "targets": [
    {
     "dataset": "timeseriesdb",
     "rawSql": "SELECT timestamp, src_ip, dest_ip, bytes_transferred, protocol, ttl, cheksum_status from timeseriesdb.packets limit 1000"
    }
   ]
  },
  {
   "title": "Data heatmap",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "timeseriesdb",
     "rawSql": "SELECT * FROM timeseriesdb.packets LIMIT 50 "
    }
   ]
  },
  {
   "title": "Correlations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "dataset": "timeseriesdb",
     "rawSql": "SELECT * FROM timeseriesdb.packets LIMIT 50 "
    }
   ]
  }
 ]
}